# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# https://docs.coderabbit.ai/guides/configure-coderabbit
language: "en-US"
early_access: false
chat: { auto_reply: true }
tone_instructions: >-
  Maintain a formal tone, highlighting issues, and suggesting production-grade, elegant, and concise solutions.

reviews:
  profile: chill
  high_level_summary: true

  # disables the cringe
  poem: true
  review_status: true

  collapse_walkthrough: true
  sequence_diagrams: true

  pre_merge_checks:
    custom_checks:
      - name: "Test Results for Major Changes"
        mode: "warning"
        instructions: |
          If this PR contains major changes, verify that the PR description includes test results or testing information.
          Pass if test results are documented or if the changes are minor.

  path_filters:
    - "!**/*.pb.go"
    - "!**/*.pb.gw.go"
    - "!**/*_pb.d.ts"

  path_instructions:
    - path: 'src/**/*.go'
      instructions: >-
        Review the Go code, point out issues relative to principles of clean
        code, expressiveness, performance, and maintainability.
    - path: 'src/test/**/*_test.**'
      instructions: >-
        Review the tests, point out issues relative to missing edge case and code quality.

  auto_review:
    drafts: false
    # disables review for new commits
    auto_incremental_review: false
    base_branches:
      - develop

  tools:
    languagetool:
      enabled: true
      level: default